SSCS-8096: Bulk scan auto – new transformation end point
hmcts/sscs-bulk-scan pull request #677
Opened 2020-09-16 20:50 UTC by srochani

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2020-09-17 08:57 UTC, jackmaloney requested changes
Could we add some integration tests for the new automated process?

2020-09-17 12:46 UTC, jackmaloney reviewed
Bit confused by the `SscsBulkScanTransformExceptionRecordCallback` test class? Isn't that just a copy and paste job of `SscsBulkScanExceptionRecordCallback` which already exists? Why do we need both?

2020-09-18 15:09 UTC, jackmaloney approved these changes

2020-09-24 13:12 UTC, srochani commented
Closing the PR as its merged with 8158 ticket https://github.com/hmcts/sscs-bulk-scan/pull/681

2020-09-24 13:12 UTC, closed without merging