SSSCS-8504:Populate venue field with the venue a case is expected to be managed from at creation
hmcts/sscs-bulk-scan pull request #775
Opened 2020-12-14 13:44 UTC by rasikasri

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/SSCS-8504

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2020-12-14 14:09 UTC, jackmaloney requested changes
Please combine the new functional test into the existing functional test. Also, can you add a test to the SscsBulkScanValidateRecordCallback class please?

2021-01-05 13:14 UTC, rasikasri commented
> Please combine the new functional test into the existing functional test. Also, can you add a test to the SscsBulkScanValidateRecordCallback class please?

Moved the new functional tests into the existing test methos in TransformationFunctionalTest. Also added an assertion into the SscsBulkScanValidateRecordCallback for processingVenue.

2021-01-05 13:43 UTC, jackmaloney commented on src/functionalTest/resources/exception/all_fields_entered_uc.json
> -      "name": "person2_title",
Were you supposed to remove these fields from this test?

2021-01-05 14:12 UTC, jackmaloney approved these changes

2021-01-14 13:59 UTC, merged